name: Build and Publish KYS.Library DocFX
permissions:
  contents: write

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - master
    paths:
      - "src/KYS.Library/**"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    env:
      KYS_LIBRARY_DOCFX_PROJECT: src/KYS.Library/docfx
      KYS_LIBRARY_DOCFX_PUBLISH_DIR: ./src/KYS.Library/docfx/_site

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Build Documentation
        working-directory: ${{ env.KYS_LIBRARY_DOCFX_PROJECT }}
        run: |
          docfx metadata
          docfx build

      # peaceiris/actions-gh-pages@v4.0.0
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.KYS_LIBRARY_DOCFX_PUBLISH_DIR }}
          destination_dir: kys-library
